"""Load and save airport YAML files."""

from __future__ import annotations

from dataclasses import asdict
from pathlib import Path

import yaml

from atc.models import Airport, Frequency, Runway


def airport_to_dict(a: Airport) -> dict:
    d = asdict(a)
    # Keep the file readable: drop empty optional values from runways.
    d["runways"] = [{k: v for k, v in r.items() if v is not None} | {"ident": r["ident"]} for r in d["runways"]]
    for key in ("spoken_name", "mag_var_deg"):  # optional, hand-added; don't write a null that hides a later edit
        if d.get(key) is None:
            d.pop(key, None)
    return d


def save_airport(a: Airport, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Generated by atc-gen, then meant to be hand-edited.\n"
        "# Fill pattern_alt_agl_ft / pattern_direction per runway, add local notes,\n"
        "# then set needs_review: false.\n"
    )
    body = yaml.safe_dump(airport_to_dict(a), sort_keys=False, allow_unicode=True)
    path.write_text(header + body, encoding="utf-8")


def load_airport(path: Path) -> Airport:
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    errors = validate_dict(raw)
    if errors:
        raise ValueError(f"{path}: " + "; ".join(errors))
    return Airport(
        icao=raw["icao"],
        name=raw["name"],
        lat=float(raw["lat"]),
        lon=float(raw["lon"]),
        elevation_ft=float(raw["elevation_ft"]),
        country=raw.get("country", ""),
        towered=bool(raw.get("towered", False)),
        language=raw.get("language", "en"),
        runways=[_runway_from_dict(r) for r in raw.get("runways", [])],
        frequencies=[Frequency(**f) for f in raw.get("frequencies", [])],
        notes=list(raw.get("notes", [])),
        needs_review=bool(raw.get("needs_review", True)),
        spoken_name=raw.get("spoken_name") or None,
        taxi_routes={str(k).zfill(2) if str(k).isdigit() else str(k): str(v) for k, v in (raw.get("taxi_routes") or {}).items()},
        mag_var_deg=float(raw["mag_var_deg"]) if raw.get("mag_var_deg") is not None else None,
    )


def _runway_from_dict(r: dict) -> Runway:
    """YAML reads an unquoted `07` as the integer 7. Runway idents are labels, so force text
    and restore the leading zero (7 -> "07"; "09L" stays as is)."""
    r = dict(r)
    ident = r["ident"]
    if isinstance(ident, int):
        ident = f"{ident:02d}"
    r["ident"] = str(ident)
    return Runway(**r)


def validate_dict(raw: dict) -> list[str]:
    errors: list[str] = []
    for key in ("icao", "name", "lat", "lon", "elevation_ft"):
        if key not in raw:
            errors.append(f"missing '{key}'")
    for r in raw.get("runways", []):
        if "ident" not in r:
            errors.append("runway without 'ident'")
        d = r.get("pattern_direction")
        if d not in (None, "left", "right"):
            errors.append(f"runway {r.get('ident')}: pattern_direction must be left/right")
    for f in raw.get("frequencies", []):
        if "kind" not in f or "mhz" not in f:
            errors.append("frequency needs 'kind' and 'mhz'")
    return errors
